services:
  - type: web
    name: preselection-qi26
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python3 app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_WHATSAPP
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/data.sqlite
